import NavBar from '@/components/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={` mt-28 ${inter.className}`}>
        <NavBar />
        {/* <div className='mx-4 sm:mx-6 lg:mx-8'> */}
          {children}
        {/* </div> */}
      </body>
    </html>
  )
}
